### PR TITLE
Make PUSI more resilient cross platform

### PR DESCRIPTION
**Pull request by narthollis**
- Add requirements.txt for specifying non-standard python modules that are required for application functionality
- Make use of pyglet library for playing media files.
  -  [pyglet](http://www.pyglet.org/) is a cross platform media library. Using AVbin pyglet can play most all media files.
- Add utils.py containing methods for use in modules
  - EVEDir is a class to determine the EVE directory path in a reliable, manor, using OS methods where possible.
  - Audio and Sound are an abstraction for playing audio files
- Allow for alternative Warp Scramble Sound
- Add .gitignore to aid in not accidental committing the wrong files.
- Make indentation consistent in pusi.pyw and various other PEP8 fixes

### CODE REVIEW

**Comment by QQHeresATissue** [comment]
These changes have mostly been implemented in other ways.  The alternative warp scramble sound would be good, but pyglet sends us down a path of requirements.  Unless I'm dumb, and it's completely possible that I am, we need a way to do this purely in python that can be included with the distribution package.

**Comment by QQHeresATissue** [comment]
bah, didnt mean to close it

**Comment by narthollis** [comment]
I understand the desire to make use of a few additional libraries as possible - but using a requirements.txt makes it very easy for end users to pull all required external modules for a project. Just ```pip install -r requirements.txt```. Some modules, such as wxPython and pywin32 which (at least on windows) require binary components still require external installation however.
The best method I have found so far for packing Python applications for Windows is cxFreeze - I also believe this can freeze applications for other platforms as well, but I as of yet have no used it outside of windows.

I started out with this patch to make a more reliable way of finding a users Documents/EVE directory, particularly on windows. The document directory is not always stored under their user directory. It can actually be stored on any UNC path, including as a network resource.
https://technet.microsoft.com/en-au/library/cc732275.aspx?f=255&MSPPError=-2147217396
In utils.EVEDir I use pywin32 to call a windows COM object to to get the correct, full path to the resource.

In regards to Pyglet, this was the result of me spending some time looking for a lite weight method of reliably playing media cross platform. Pyglet seamed to be the only project that was both lite weight and still active. By default it is pure Python, and could be included in your project distribution (assuming licence compatibility), with the use of AVbin pyglet has the ability to play a wide variety of audio formats (I am currently using it to play mp3's i downloaded from CCP's SoundCloud)

**Comment by narthollis** [comment]
If you would like, when I update this pull for your new code, I will break the pull request down into better finding the documents directory and using pyglet for cross platform audio.

**Comment by QQHeresATissue** [comment]
The real issue is can the average goon handle this.  I think the answer is no.  People have already requested installers, etc.  Relying on more installs just makes it confusing.

Switching to expanduser should have fixed the pathing issues.

Pyglet I agree with.  This would be the best way to handle it, and streamlines the code down, but its also an external dependency.  Is it possible to just do the pip installs from within?  I've never done this before, but I suppose doing a check for pyglet like what is done with wxPython would be acceptable.

**Comment by QQHeresATissue** [comment]
To better expand on the last bit, if we dont find pyglet, prompt them to hit a button that does the pip install, or give them the line to do so.

**Comment by narthollis** [comment]
The best way to deal with users not being able to / not wanting to bother with dependencies would be to use a packaging system like cxFreeze, this will freeze all of the project dependence inside a single package. (This will also let you create a .exe for windows, which means people wont even need to install Python and wxPython)

The problem with expand user is that it is possible for a users documents directory to not be under their home directory, eg.
```
Home: c:\users\administrator\
Documents: d:\documents\
```
In this case, ```expanduser('~/Documents/')``` will resolve to ```c:\users\administrator\Documents\``` instead of the correct path ```d:\documents\```.

**Comment by QQHeresATissue** [comment]
I would rather not do the executable thing when supplying the script is enough.  Mainly because I don't think that distributing it as an executable is necessary, but also because no one should trust random executables.  Finally, this is only an issue on windows, and to maintain a separate step just for that is meh.  

I see your point here.  I think it is unlikely that the majority would have this type of setup, but I suppose it's possible.  If you want to fix it up for the latest I can merge it in easy.

**Comment by narthollis** [comment]
I will look into if/how to include pyglet and pywin32 as part of the distribution without requiring additional installs to be kicked off by the user. I will also create a clean patch for better resolving the EVE directory.

**Comment by tehFred** [comment]
You are really at the stage where you should be compiling this into a single executable, goons + dealing with dependencies never works well. It's not a simple script anymore, you already need people to get python and wxpython so you should be compiling it. 

My documents folder isn't on part of my C: either and I spent a while fixing this that I'd rather not have. Enough goons are using this tool now that it needs to be done.

If people are asking for installers then a single executable is going to be FAR easier to do.

**Pull request closed without merging**
